### ISSUE TITLE
Simplify invitation messages

### ISSUE THREAD

**Issue by kierio04** [crackhex/TAS-Comp-Bot-py#6]
- [x] If an invitee presses "Accept", the bot edits the message to `<invitee> has accepted the collaboration`
- [x] If an invitee presses "Decline", the bot edits the message to `<invitee> has declined the collaboration`
- [x] If an invitee presses "Decline", the bot **doesn't** send `<invitee> declined the collaboration. Others can still accept`
- [x] If the leader presses "Cancel", the bot edits the message to `The the collaboration request to <invitee> has been cancelled`
- [x] If the leader presses "Cancel", the bot **doesn't** send `<leader> has cancelled the collaboration request to <invitee>`
- [x] If an invite times out, the bot edits the message to `The collaboration request to <invitee> has timed out`
- [x] If a team is formed, the bot sends `<leader> is now collaborating with <invitees...>`
- [x] If a team is formed, the bot **doesn't** check if there were cancellations and send `Despite the cancellations, <leader> will collaborate with <invitees...>`
- [x] If no team is formed, the bot sends `No team has been formed as all invitations were declined, cancelled, or timed out`
- [x] If a team is updated, the bot sends `<invitee> has been added to your team`
- [x] If a team is not updated, the bot sends `Nobody has been added to your team as all invitations were declined, cancelled, or timed out`

When collab tasks start, #seeking-partners will evidently become chaotic with several invitations being sent at once. The point of this is to minimise the number of messaged by ensuring only the invitations and the final result of the invitations (i.e. team formed or no team formed) are the messages sent. The messages themselves are also simplified to prevent having to track lots of cases for large team sizes.

**Comment by Dash-QC** [comment]
Fixed in https://github.com/crackhex/TAS-Comp-Bot-py/commit/f516f901c44c043a48d6dffcd8f2d3b4d27da295.

**Comment by kierio04** [comment]
Reopening as issue wasn't quite resolved, and new edge cases were realised.
- A few messages simply need to be reworded
- The "Despite the cancellations" case still needs to be removed
- The distinction between team formation and team update means a couple new messages

**Comment by kierio04** [comment]
Fixed in f0bc1dd. Closing for good now.
